import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Box, Button, Flex, Text, Image, Input, Icon } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { IoHeartSharp } from "react-icons/io5";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const HeartsShape = () => {
  return (
    <Flex gap={1}>
      <Icon as={IoHeartSharp} />
      <Icon as={IoHeartSharp} />
      <Icon as={IoHeartSharp} />
    </Flex>
  );
};

// https://api.whatsapp.com/send?phone=6282119529495&text=Halo%20WA%20Wedding%20Mau%20tanya%20info%20pricelist%20*Kota%20Bandung*%20dong....
// Hai%20sayaangggg%0Akita%20ngedate%20yakkk%20tanggal%2011-09-2024%0Ake%20asaan%20kopi
export default function Home() {
  const [statePage, setStatePage] = useState("initial");
  const [countDown, setCountDown] = useState(5);
  const [date, setDate] = useState();
  const [place, setPlace] = useState();
  const myNumber = "6285156167218";
  const loacationList = [
    {
      name: "Asaan Kopi",
      imageUrl:
        "https://fastly.4sqi.net/img/general/600x600/2127998_COn0NAh1ZhQ07gF7Xf3-_drgxLC_ehL4xQfTG5xdG6E.jpg",
    },
    {
      name: "Imago",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUMRA-oHG78C9QH54QiQpdDXYMYJgOGQb1ew&s",
    },
    {
      name: "372 Dago",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTifQDCPBDEXIfBMaNY82l0i19kdxESuImtMg&s",
    },
    {
      name: "Urbane Dago",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo3KSEcoE2Z3C4pSmzwQGbsobo2LvjbQI2XA&s",
    },
    {
      name: "Cascara Coffee",
      imageUrl:
        "https://assets-pergikuliner.com/3MhKG3gtu0p96Q3A-q377QPg4rQ=/312x0/smart/https://assets-pergikuliner.com/uploads/image/picture/1205764/picture-1546017378.jpg",
    },
    {
      name: "Edelweiss cafe",
      imageUrl:
        "https://assets-pergikuliner.com/WE6f5zjeC1FW5yXL5tvk4uNE13s=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2399065/picture-1641489860.JPG",
    },
    {
      name: "Teras Pinus",
      imageUrl:
        "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p2/74/2024/01/03/20240103_184234-4067825317.jpg",
    },
    {
      name: "Seblak Mama Saleh",
      imageUrl:
        "https://www.pintuberita.com/wp-content/uploads/2024/01/SEBLAK.jpg",
    },
  ];

  useEffect(() => {
    if (!statePage) {
      setStatePage("initial");
    }
  }, [statePage]);

  useEffect(() => {
    if (statePage === "She-Wants-Date" && countDown > 0) {
      const interval = setInterval(() => {
        setCountDown((prev) => prev - 1);
      }, 1000);
      return () => clearInterval(interval);
    }
  }, [statePage]);
  return (
    <>
      <Head>
        <title>For Acaa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Flex justifyContent="center" alignItems="center" minH="100vh">
          {statePage === "decline" && (
            <Box textAlign="center">
              <Box rounded="lg" overflow="hidden" w="250px" h="auto">
                <Image
                  alt="sad-cat"
                  src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW5iY3J3YTJvZXpodHdwdnVqMW1mZzI2dzlscjZ0Zm92a3NnMDBsdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qbSt4saiie3ZgxZJY8/giphy.webp"
                />
              </Box>
              <Text
                fontWeight="bold"
                color="pink.500"
                fontSize="2xl"
                mt={4}
                mb={4}
              >
                {"Please :(((("}
              </Text>
              <Button
                onClick={() => setStatePage("initial")}
                colorScheme="pink"
                variant="outline"
                size="sm"
              >
                Okay Okay Im Sorry
              </Button>
            </Box>
          )}
          {statePage === "initial" && (
            <Box>
              <div
                style={{
                  width: "100%",
                  height: "0",
                  paddingBottom: "100%",
                  position: "relative",
                }}
              >
                <Image
                  src="https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExdXhtYm10cjAxaGxqYm90ZjdxbGd5eTg3cXU4MGg1ZnZ2ZmU3cTVkYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l4Ki4biBSwhjyrS48/giphy.webp"
                  width="100%"
                  height="100%"
                  style={{ position: "absolute" }}
                  alt="Love-Rose"
                />
              </div>
              <Text fontSize="2xl" color="pink.500" fontWeight="bold">
                Would you like to Date With Me ?
              </Text>
              <Flex gap={10} alignItems="center" justifyContent="center" mt={6}>
                <Button
                  colorScheme="pink"
                  variant="outline"
                  onClick={() => setStatePage("decline")}
                >
                  No
                </Button>
                <Button
                  colorScheme="pink"
                  onClick={() => setStatePage("She-Wants-Date")}
                  leftIcon={<HeartsShape />}
                  rightIcon={<HeartsShape />}
                >
                  Yes
                </Button>
              </Flex>
            </Box>
          )}

          {statePage === "She-Wants-Date" && (
            <Flex
              flexDirection="column"
              alignItems="center"
              justifyContent="center"
            >
              <Box rounded="lg" overflow="hidden" w="250px" h="auto">
                <Image
                  src="https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExcW11YTZ5OGw4MTN0Z2Rvcnh1M3J2anJhMHk4YnF3anR1aDJmZmZsNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MziKDo6gO7x8A/giphy.webp"
                  width="100%"
                  height="100%"
                  alt="happy-cat"
                />
              </Box>
              <Text fontSize="2xl" color="pink.500" fontWeight="bold" mt={4}>
                Horrayyy!!!! please wait for a moment...
              </Text>
              <Flex gap={10} alignItems="center" justifyContent="center" mt={6}>
                {countDown > 0 ? (
                  <Text fontSize="3xl" color="pink.500" fontWeight="bold">
                    {countDown}
                  </Text>
                ) : (
                  <Button
                    colorScheme="pink"
                    onClick={() => setStatePage("Pick-Date")}
                    leftIcon={<HeartsShape />}
                    rightIcon={<HeartsShape />}
                  >
                    Lets pick a date
                  </Button>
                )}
              </Flex>
            </Flex>
          )}

          {statePage === "Pick-Date" && (
            <Flex flexDirection="column" alignItems="center" gap={4}>
              <Box rounded="lg" overflow="hidden" w="250px" h="auto">
                <Image
                  alt="looking-cat"
                  src="https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJzcGlzNWZxdDBiMWk2Nmg4amJlZzRuYTRtY3Y5MnkyYXR0MjJzciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wollgOXZPyUYvxht3V/giphy.webp"
                />
              </Box>
              <Text
                fontWeight="bold"
                color="pink.500"
                fontSize="2xl"
                mt={4}
                mb={4}
              >
                When are you free ?
              </Text>

              <Input type="date" onChange={(e) => setDate(e?.target?.value)} />

              <Button
                onClick={() => setStatePage("pick-location")}
                colorScheme="pink"
                leftIcon={<HeartsShape />}
                rightIcon={<HeartsShape />}
              >
                Im Ready
              </Button>
            </Flex>
          )}

          {statePage === "pick-location" && (
            <Flex flexDirection="column" alignItems="center">
              <Text fontSize="3xl" color="pink.500" mb={10}>
                Lets pick a location {"<3 <3 <3"}
              </Text>
              <Flex
                flexDirection="row"
                justifyContent="center"
                gap={6}
                flexWrap="wrap"
              >
                {loacationList.map((loc, index) => (
                  <Box
                    p={4}
                    rounded="lg"
                    key={index}
                    border="2px solid gray"
                    textAlign="center"
                    _hover={{ background: "pink.50" }}
                    cursor="pointer"
                    onClick={() => setPlace(loc?.name)}
                    background={place === loc?.name ? "pink.100" : "white"}
                  >
                    <Box
                      rounded="lg"
                      overflow="hidden"
                      w={{ base: "100px", lg: "250px" }}
                      h={{ base: "100px", lg: "250px" }}
                    >
                      <Image
                        src={loc?.imageUrl}
                        width="100%"
                        height="100%"
                        alt="location"
                      />
                    </Box>
                    <Text mt={4} fontWeight="semibold" fontSize="lg">
                      {loc?.name}
                    </Text>
                  </Box>
                ))}
              </Flex>
              <Button
                mt={4}
                mb={8}
                colorScheme="pink"
                onClick={() => {
                  window.open(
                    `https://api.whatsapp.com/send?phone=${myNumber}&text=Hai%20sayaangggg%0Akita%20ngedate%20yakkk%20tanggal%20${date}%0Ake%20${place}%20%F0%9F%A5%B0%F0%9F%A5%B0%F0%9F%A5%B0%F0%9F%A5%B0%F0%9F%A5%B0`,
                    "_blank"
                  );
                  setStatePage("thanks");
                }}
                leftIcon={<HeartsShape />}
                rightIcon={<HeartsShape />}
              >
                Send Me Messeage
              </Button>
            </Flex>
          )}

          {statePage === "thanks" && (
            <Flex
              flexDirection="column"
              justifyContent="center"
              alignItems="center"
            >
              <Box rounded="lg" overflow="hidden" w="250px" h="auto">
                <Image
                  alt="happy-cat"
                  src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnFidjIzNnU2MnB2a2p0cmJ0NWpseTBqcm5hb3kzODd1amQzMXI5MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/lck9f0L8jPjRtkigYy/giphy.webp"
                />
              </Box>
              <Text
                fontWeight="bold"
                color="pink.500"
                fontSize="2xl"
                mt={4}
                mb={4}
              >
                {"Thank Youu Sayanggg <3 <3 <3 <3, Tunggu aku jemput yaaak !!!"}
              </Text>
              <Button
                onClick={() => setStatePage("initial")}
                colorScheme="pink"
                variant="outline"
                leftIcon={<HeartsShape />}
                rightIcon={<HeartsShape />}
              >
                Okaaay Sayaang
              </Button>
            </Flex>
          )}
        </Flex>
      </div>
    </>
  );
}
